# services:
#   norma-db:
#     container_name: norma-db
#     ports:
#       - 3366:3306    
#     expose:
#       - "3366"
#     image: "mysql:latest"
#     environment:
#       MYSQL_ROOT_PASSWORD: admin
#       MYSQL_DATABASE: norma-db
#     healthcheck:
#       test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#       timeout: 10s
#       retries: 10
#       interval: 10s
#       start_period: 10s
  
#   rabbitmq:
#     container_name: norma-rabbitmq
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672" # AMQP protocol port for your application to connect
#       - "15672:15672" # Management UI port
#     expose:
#       - "5672"
#       - "15672"
#     healthcheck:
#       test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
  
#   norma:
#     ports:
#       - 9530:9530
#     image: "mowumi/norma:v1"
#     container_name: norma-ms
#     depends_on:
#       norma-db:
#         condition: service_healthy
#       rabbitmq:
#         condition: service_healthy
#     environment:
#       SPRING_APPLICATION_NAME: "norma"
#       SPRING_PROFILES_ACTIVE: default
#       SPRING_DATASOURCE_URL: "jdbc:mysql://norma-db:3306/norma-db?useSSL=false&allowPublicKeyRetrieval=true"
#       SPRING_DATASOURCE_USERNAME: "root"
#       SPRING_DATASOURCE_PASSWORD: "admin"
#       SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
#       JWT_SECRET: "${JWT_SECRET}"
#       PAYSTACK_SECRET: ${PAYSTACK_SECRET}
#       MAIL_PASSWORD: ${MAIL_PASSWORD}
#       MAIL_USERNAME: ${MAIL_USERNAME}
#       ADMIN_EMAIL: ${ADMIN_EMAIL}
#       SPRING_RABBITMQ_HOST: "rabbitmq"
#       SPRING_RABBITMQ_PORT: 5672
#       SPRING_RABBITMQ_USERNAME: "guest"
#       SPRING_RABBITMQ_PASSWORD: "guest"
#       CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
#       CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
#       CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      


# networks:
#   norma:
#     driver: "bridge"