server:
    port: 9530

spring:
    application:
        name: norma
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    jpa:
        properties:
            hibernate:
                format_sql: "true"
        hibernate:
            ddl-auto: update
        show-sql: "true"
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        # url: jdbc:mysql://hotel-services-db:3306/hotel-services-db?useSSL=false&allowPublicKeyRetrieval=true
        url: jdbc:mysql://127.0.0.1:3306/norma-db
        username: root
        password: admin

app:
    jwtSecret: "${JWT_SECRET}"
    jwtExpirationMS: 7200000

paystack:
    base-url: https://api.paystack.co
    secret-key: ${PAYSTACK_SECRET}


googleDrive:
    hotel-images-folder-id: {HOTEL_IMAGES_FOLDER_ID}
    room-images-folder-id: {ROOM_IMAGES_FOLDER_ID}