server:
    port: 9530

spring:
    application:
        name: norma
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD:xwrnvhrfhyxjrmgj}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    jpa:
        properties:
            hibernate:
                format_sql: "true"
        hibernate:
            ddl-auto: update
        show-sql: "true"
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        # url: jdbc:mysql://hotel-services-db:3306/hotel-services-db?useSSL=false&allowPublicKeyRetrieval=true
        url: jdbc:mysql://127.0.0.1:3306/norma-db
        username: root
        password: admin

    # rabbitmq:
    #     host: ${SPRING_RABBITMQ_HOST:localhost}
    #     port: ${SPRING_RABBITMQ_PORT:5672}
    #     username: guest
    #     password: guest


app:
    jwtSecret: "${JWT_SECRET}"
    jwtExpirationMS: 7200000

paystack:
    base-url: https://api.paystack.co
    secret-key: ${PAYSTACK_SECRET}

adminEmail: ${ADMIN_EMAIL}

cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}
